--1
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED;
--2
SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED;
--1
BEGIN;
--2
BEGIN;
--1
SELECT SUM(rating) FROM pizzeria;
--2
UPDATE pizzeria SET rating = 1 WHERE name = 'Pizza Hut';
COMMIT;
--1
SELECT SUM(rating) FROM pizzeria;
COMMIT;
--1
SELECT SUM(rating) FROM pizzeria;

--2
SELECT SUM(rating) FROM pizzeria;